version: "3.9"

services:
  redis:
    image: redis:alpine
    networks:
      - todonet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    secrets:
      - redis_password

  backend:
    image: maria-backend:1.0
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/db
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - todonet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    command: ["/bin/sh", "-c", "while ! nc -z redis 6379; do sleep 1; done && uvicorn main:app --host 0.0.0.0 --port 8000"]
    secrets:
      - redis_password
      - db_password

  frontend:
    image: maria-frontend:1.0
    ports:
      - "80:80"
    networks:
      - todonet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    configs:
      - source: frontend_config
        target: /app/config.js

  nginx:
    image: todo-nginx:1.0
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - todonet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  db_data:

networks:
  todonet:

secrets:
  redis_password:
    file: ./secrets/redis_password.txt
  db_password:
    file: ./secrets/db_password.txt

configs:
  frontend_config:
    file: ./frontend/config.js