apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: maria-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: mgonzalesl/maria-worker:1.0
          envFrom:
            - secretRef:
                name: maria-secret
